const CACHE_PREFIX = 'workout-routine-pwa-';
const CACHE_NAME = CACHE_PREFIX + 'v96-release-96';
const RELEASE = CACHE_NAME.match(/v(\d+)-release-/)[1];
const BASE = '/workout-app/';
// Generated by bump-version.sh. Do not edit these hashes manually.
const ASSET_HASHES = {"index.html":"1b5a8f19a210502d9eea3b133ec18947f2177d3757715992031cc51042d1f827","app.js":"1c1c2c97423046f71a8958f96830145e97e3abc7002835140b54bd06b1c46506","style.css":"f9b88d71c2fd168e03799f470c851affe82453d3e8d65487039d65cac0f839a5"};
const APP_SHELL = [BASE+'index.html',BASE+'style.css?v='+RELEASE,BASE+'app.js?v='+RELEASE,BASE+'manifest.webmanifest',BASE+'icon-192.png',BASE+'icon-512.png'];
const clientReleases = new Map();
async function cleanupUnusedReleases(){
  const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});
  const scoped=clients.filter(client=>new URL(client.url).pathname.startsWith(BASE));
  // Unknown clients may still be using an older release; retain their caches.
  if(scoped.some(client=>!clientReleases.has(client.id)))return;
  const keep=new Set([CACHE_NAME]);
  scoped.forEach(client=>{const v=clientReleases.get(client.id);keep.add(CACHE_PREFIX+'v'+v+'-release-'+v);});
  await Promise.all((await caches.keys()).filter(key=>key.startsWith(CACHE_PREFIX) && !keep.has(key) && Number((key.match(/v(\d+)-release-/)||[])[1])<Number(RELEASE)).map(key=>caches.delete(key)));
}

function unavailable(){return new Response('앱 파일을 준비하지 못했어요. 연결 후 다시 열어주세요.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});}
async function verifiedResponse(path){
  const response=await fetch(new Request(path,{cache:'reload'}));
  if(!response.ok)throw new Error('Asset fetch failed: '+path);
  const name=new URL(path,self.location.origin).pathname.slice(BASE.length);
  if(Object.prototype.hasOwnProperty.call(ASSET_HASHES,name)){
    const digest=await crypto.subtle.digest('SHA-256',await response.clone().arrayBuffer());
    const hex=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');
    if(hex!==ASSET_HASHES[name])throw new Error('Release asset mismatch: '+name);
  }
  return response;
}
self.addEventListener('install',event=>{
  event.waitUntil((async()=>{
    const responses=await Promise.all(APP_SHELL.map(verifiedResponse));
    const cache=await caches.open(CACHE_NAME);
    await Promise.all(APP_SHELL.map((path,i)=>cache.put(path,responses[i])));
  })());
});
self.addEventListener('message',event=>{
  if(event.data && event.data.type==='SKIP_WAITING')event.waitUntil(self.skipWaiting());
  if(event.data && event.data.type==='CLIENT_RELEASE' && event.source && /^\d+$/.test(String(event.data.version))){
    clientReleases.set(event.source.id,String(event.data.version));
    event.waitUntil(cleanupUnusedReleases());
  }
});
self.addEventListener('activate',event=>{
  // Keep previous releases for other open tabs using their versioned URLs.
  event.waitUntil(self.clients.claim());
});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const url=new URL(event.request.url);
  if(url.origin!==self.location.origin || !url.pathname.startsWith(BASE))return;
  if(url.pathname===BASE+'index.html' && url.searchParams.get('update-check')==='1'){
    event.respondWith(fetch(event.request,{cache:'no-store'}).catch(unavailable));return;
  }
  const name=url.pathname.slice(BASE.length);
  const navigation=event.request.mode==='navigate';
  if(navigation || name==='' || name==='index.html'){
    event.respondWith(caches.open(CACHE_NAME).then(cache=>cache.match(BASE+'index.html')).then(hit=>hit || unavailable()));return;
  }
  if(name==='app.js' || name==='style.css'){
    const version=url.searchParams.get('v');
    const requested=version && /^\d+$/.test(version)?version:RELEASE;
    const cacheName=CACHE_PREFIX+'v'+requested+'-release-'+requested;
    event.respondWith((async()=>{
      const cache=await caches.open(cacheName);
      return await cache.match(BASE+name+'?v='+requested) ||
        (!version?await cache.match(BASE+name):null) || unavailable();
    })());return;
  }
  if(APP_SHELL.includes(url.pathname)){
    event.respondWith(caches.open(CACHE_NAME).then(cache=>cache.match(url.pathname)).then(hit=>hit || unavailable()));
  }
});
